### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by gcavalcantes** [GabrielCavalcanteS/ProblemaTroco#1]
Lista de coisas a serem feitas para completar este projeto:
## Pesquisa
- [x] Criar um documento para elaborar sobre o problema e registrar todo o projeto.
- [x] Pesquisar sobre o problema.
- [x] Documentar a pesquisa no documento criado.
- [x] Documentar código ao término do desenvolvimento.
- [x] Converter o documento da pesquisa para PDF.
- [x] Adicionar o PDF ao projeto.
## Desenvolvimento
- [x] Criar método para mostrar mensagem do troco.
- [x] Verificar se a solução desenvolvida obedece aos critérios descritos para o trabalho. 
- [x] Testar com valores diferentes.

**Comment by gcavalcantes** [comment]
Todos os objetivos alcançados. Este projeto está completo.
